---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 127.0.0.1
      ansible_user: centos

vector:
  hosts:
    vector-01:
      ansible_host: 127.0.0.2
      ansible_user: centos

lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 127.0.0.3
      ansible_user: centos
